### PR TITLE
Cluster documentation update for next release [WIP]

### PR DESCRIPTION
**Pull request by JoeriHermans**
Work in progress to discuss the cluster documentation.

### CODE REVIEW

**Comment by glouppe** [comment]
todo: add a paragraph on `seff`

**Comment by glouppe** [comment]
* [ ] The registration link at the beginning of User account setup should be updated.
* [ ] add a paragraph on seff

**Comment by glouppe** [comment]
In the GPU usage section, shall we also explain how to pre-buffer data in order to reduce GPU idling?

**Comment by JoeriHermans** [comment]
I'll combine these comments by adding a section 'Example usage' or 'Workflow'.

Will be like this:
1) Initial guess on job resources.
2) Run on `debug` partition
3) Evaluate resource consumption with `seff`
4) Adjust parameters accordingly
5) Verify again on `debug`
6) Run on desired partition

Something lke this.

**Comment by JoeriHermans** [comment]
What do you mean with pre-buffering exactly? Loading it into memory, or the tuning of the DataLoaders?

**Pull request merged**
